export const Data = [
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
  {
    _id: "1",
    Name: "John Doe",
    Role: "Software Engineer",
    Experience: "5 years",
    Skills: "React, Node.js",
  },
  {
    _id: "2",
    Name: "Jane Smith",
    Role: "Data Scientist",
    Experience: "3 years",
    Skills: "Python, R, SQL",
  },
];
